// The exact error code catalog from LLD §52 -- every thrown domain error in
// this service uses one of these, never an ad hoc string, so the client's
// error handling stays a fixed, documented contract.

export const MESSAGING_ERRORS = {
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  MESSAGING_DISABLED: 'MESSAGING_DISABLED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  RECIPIENT_NOT_FOUND: 'RECIPIENT_NOT_FOUND',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_NOT_ACTIVE: 'CONVERSATION_NOT_ACTIVE',
  REQUEST_REQUIRED: 'REQUEST_REQUIRED',
  REQUEST_PENDING: 'REQUEST_PENDING',
  REQUEST_ALREADY_SENT: 'REQUEST_ALREADY_SENT',
  REQUEST_NOT_ALLOWED: 'REQUEST_NOT_ALLOWED',
  MESSAGE_LIMIT_REACHED: 'MESSAGE_LIMIT_REACHED',
  DUPLICATE_MESSAGE: 'DUPLICATE_MESSAGE',
  DEVICE_REVOKED: 'DEVICE_REVOKED',
  KEY_INVALID: 'KEY_INVALID',
  MESSAGE_TOO_LARGE: 'MESSAGE_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_PROTOCOL: 'INVALID_PROTOCOL',
} as const;

export type MessagingErrorCode =
  (typeof MESSAGING_ERRORS)[keyof typeof MESSAGING_ERRORS];
